name: build

on:
  push:
    paths:
      - 'caddy-linux-amd64.md'
  schedule:
    - cron: "0 0 * * Sat"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@master
      with:
#        stable: 'false'
        go-version: '^1.18.3'
    - name: prepare
      run: |
        wget https://github.com/caddyserver/xcaddy/releases/download/v0.3.0/xcaddy_0.3.0_linux_amd64.tar.gz
        tar -zxvf xcaddy_0.3.0_linux_amd64.tar.gz
        chmod +x ./xcaddy

    - name: build
      run: |
        export GOARCH=amd64
        export GOOS=linux
        ./xcaddy build \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/mholt/caddy-webdav \
          --with github.com/imgk/caddy-trojan \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy